base_directory = "."
[[path_mappings]]
repo_path= "nvim/"
host_path = ".config/nvim/"
related_program = "neovim"

[[path_mappings]]
repo_path= "alacritty/"
host_path= ".config/alacritty/"

[[path_mappings]]
repo_path= "hyprland/"
host_path = ".config/hypr/"
[[path_mappings]]
repo_path= "waybar"
host_path = ".config/waybar/"
[[path_mappings]]
repo_path= "sway"
host_path = ".config/sway/"
[[path_mappings]]
repo_path= "swaylock"
host_path = ".config/swaylock/"

[[path_mappings]]
repo_path= "zsh"
host_path = ".config/zsh/"
[[path_mappings]]
repo_path= "zsh/.zshenv"
host_path = ".zshenv"
[[path_mappings]]
repo_path= "fuzzel"
host_path = ".config/fuzzel/"
[[path_mappings]]
repo_path= "starship/"
host_path = ".config/starship/"
[[path_mappings]]
repo_path= "fontconfig/"
host_path = ".config/fontconfig/"
[[path_mappings]]
repo_path= "aerospace/"
host_path = ".config/aerospace/"

[[path_mappings]]
repo_path= "sketchybar/"
host_path = ".config/sketchybar/"
[[path_mappings]]
repo_path= "karabiner/"
host_path = ".config/karabiner/"
[[path_mappings]]
repo_path= "aerospace-swipe/"
host_path = ".config/aerospace-swipe/"
[[path_mappings]]
repo_path= "electron/electron-flags.conf"
host_path = ".config/electron-flags.conf"
[[path_mappings]]
repo_path= "kde/kdeglobals"
host_path = ".config/kdeglobals"

[[path_mappings]]
repo_path= "opencode/agent"
host_path = ".config/opencode/agent"

[[path_mappings]]
repo_path= "opencode/tool"
host_path = ".config/opencode/tool"

[[path_mappings]]
repo_path= "opencode/package.json"
host_path = ".config/opencode/package.json"

[[path_mappings]]
repo_path= "opencode/bun.lock"
host_path = ".config/opencode/bun.lock"

[[path_mappings]]
repo_path= "opencode/opencode.jsonc"
host_path = ".config/opencode/opencode.jsonc"

